Traceback (most recent call last):
  File "/home/nicola/.pyenv/versions/3.8.5/envs/cuda/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/nicola/.pyenv/versions/3.8.5/envs/cuda/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/nicola/.pyenv/versions/3.8.5/envs/cuda/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/nicola/.pyenv/versions/3.8.5/envs/cuda/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/nicola/.pyenv/versions/3.8.5/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/nicola/.pyenv/versions/3.8.5/envs/cuda/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/home/nicola/.pyenv/versions/3.8.5/envs/cuda/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/nicola/.pyenv/versions/3.8.5/envs/cuda/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
print('best model & score')
# pprint(linear_search.best_params_, compact=True)
# print(linear_search.best_score_)
pprint({'Classifier__criterion': 'gini',
 'Classifier__max_depth': 50,
 'Classifier__max_features': 'auto',
 'Classifier__n_estimators': 50,
 'Classifier__oob_score': True,
 'Classifier__random_state': 42})
print(0.8687141522110355)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-6-44284ad06cff>[0m in [0;36m<module>[0;34m[0m
[1;32m      2[0m [0;31m# pprint(linear_search.best_params_, compact=True)[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0;31m# print(linear_search.best_score_)[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 4[0;31m pprint({'Classifier__criterion': 'gini',
[0m[1;32m      5[0m  [0;34m'Classifier__max_depth'[0m[0;34m:[0m [0;36m50[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m      6[0m  [0;34m'Classifier__max_features'[0m[0;34m:[0m [0;34m'auto'[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'pprint' is not defined
NameError: name 'pprint' is not defined

