Traceback (most recent call last):
  File "/home/nicola/.pyenv/versions/3.8.5/envs/cuda/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/nicola/.pyenv/versions/3.8.5/envs/cuda/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/nicola/.pyenv/versions/3.8.5/envs/cuda/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/nicola/.pyenv/versions/3.8.5/envs/cuda/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/nicola/.pyenv/versions/3.8.5/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/nicola/.pyenv/versions/3.8.5/envs/cuda/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/home/nicola/.pyenv/versions/3.8.5/envs/cuda/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/nicola/.pyenv/versions/3.8.5/envs/cuda/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
sns.set_theme()
# sns.set_style("dark")

bandwidth=1/np.std(data)

# Compute KDE by hand
samples = 200


# grid points
xmin = min(data) - 3 * width
xmax = max(data) + 3 * width

x = np.linspace(xmin, xmax, samples)

# compute kde
kde = np.zeros(samples)

kdes = []
for val in data:
    kdes.append(norm.pdf(x, loc=val, scale=width))
kde = np.sum(kdes, axis=0)

# normalize
norm_fact = sp.integrate.simps(kde, x)
kde /= norm_fact

# Plot against seaborn kde
ax = sns.kdeplot(data, label="seaborn", bw_method=bandwidth)
ax = sns.lineplot(x=x, y=kde, label="KDE")

for kd in kdes:
    sns.lineplot(x=x, y=kd/norm_fact, ax=ax, palette="Paired")
    
for line in ax.lines[1:]:
    line.set_linestyle("--")
    
    
sns.rugplot(data, ax=ax, palette="Paired")

plt.legend();
plt.show()
------------------

[0;31m-------------------------------------------------------------[0m
[0;31mNameError[0m                   Traceback (most recent call last)
[0;32m<ipython-input-5-ef04795965f7>[0m in [0;36m<module>[0;34m[0m
[1;32m      9[0m [0;34m[0m[0m
[1;32m     10[0m [0;31m# grid points[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 11[0;31m [0mxmin[0m [0;34m=[0m [0mmin[0m[0;34m([0m[0mdata[0m[0;34m)[0m [0;34m-[0m [0;36m3[0m [0;34m*[0m [0mwidth[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     12[0m [0mxmax[0m [0;34m=[0m [0mmax[0m[0;34m([0m[0mdata[0m[0;34m)[0m [0;34m+[0m [0;36m3[0m [0;34m*[0m [0mwidth[0m[0;34m[0m[0;34m[0m[0m
[1;32m     13[0m [0;34m[0m[0m

[0;31mNameError[0m: name 'width' is not defined
NameError: name 'width' is not defined

